//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int StudentsId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Age { get; set; }
        public Nullable<int> ClassId { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Classes Classes { get; set; }
    }
}
